### ISSUE TITLE
Report link missing on last level

### ISSUE THREAD

**Issue by Vernal** [postmatic/crowd#1]
Automatic mode implementation currently does not work with threaded comments in the last level of threading. As the script attaches itself to the comment_reply which is not displayed once the maximum threading level is reached the abuse link is missing at this point.

**Comment by Vernal** [comment]
There are two ways this could shake out:
1. We make it work by hooking into something else..... or...
2. We leave it alone and instead conditionally call comment_report_abuse_link in Epoch instead.

**Comment by ronalfy** [comment]
Fixed https://github.com/postmatic/safe-report-comments/commit/044635ac4ca11fea51de4acca377d727edca4375

Added css `last-thread` so you can style it appropriately.

**Comment by ronalfy** [comment]
I think this is proof I shouldn't program buzzed and tired.

Should be fixed here. https://github.com/postmatic/safe-report-comments/commit/92883dae148f37e65c7fbdc6af4bf74348f57c3e

Can you close if satisfied?

**Comment by Vernal** [comment]
Bahahahhahaaaa. Nice.
