### ISSUE TITLE
Submit Plugin to Repo

### ISSUE THREAD

**Issue by ronalfy** [postmatic/crowd#15]
As soon as https://github.com/postmatic/crowd/issues/13 and https://github.com/postmatic/crowd/issues/5 let's create a .org branch and submit that as the zip.

Sounds good @Vernal  ?

**Comment by soderlind** [comment]
If you'd like, I can create the  [Gruntfile.js](https://github.com/soderlind/read-offline/blob/master/Gruntfile.js) needed to submit the plugin to .org

It gives you the folowing options (I could strip it down to `pre_vcs` and `do_svn`):

```
    grunt release (pre_vcs, do_svn, do_git, clean:post_build)
    grunt pre_vcs (update plugin version number in files, make languages/.pot)
    grunt do_svn (svn_export, copy:svn_trunk, copy:svn_tag, push_svn)
    grunt do_git (gitattributes, gitcommit, gittag, gitpush)
```

**Comment by Vernal** [comment]
Hey Per!

Thanks so much for the offer. I think we have a solid deployment process
lined up already though. We have a script which we've been using on Epoch
that is near-perfect.

How did Crowd catch your eye? Your plugins are great. I've used a few
before. If you are interested in commenting plugins Epoch is the one that
needs all hands on deck. We'd love any contributions you can make at
https://github.com/postmatic/epoch/labels/help%20wanted.

Be in touch,
Jason

On Tue, Sep 22, 2015 at 10:57 AM, Per Søderlind notifications@github.com
wrote:

> If you'd like, I can create the Gruntfile.js
> https://github.com/soderlind/read-offline/blob/master/Gruntfile.js
> needed to submit the plugin to .org
> 
> It gives you the folowing options (I could strip it down to pre_vcs and
> do_svn):
> 
> ```
> grunt release (pre_vcs, do_svn, do_git, clean:post_build)
> grunt pre_vcs (update plugin version number in files, make languages/.pot)
> grunt do_svn (svn_export, copy:svn_trunk, copy:svn_tag, push_svn)
> grunt do_git (gitattributes, gitcommit, gittag, gitpush)
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/crowd/issues/15#issuecomment-142313351.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by Vernal** [comment]
Oh, I see. Ronald had applied the Help Wanted label on this one. Sorry about that. I've got it covered :)

**Comment by soderlind** [comment]
No problem :) I found this plugin through epoch (had to look at your other repos).

Can crowd coexist with epoch or do you plan to add the functionality to epoch? I need the crowd moderation for a site I'm working on.

**Comment by ronalfy** [comment]
Still tweaking, but we'ee at a loont that it is repo ready.

**Comment by Vernal** [comment]
It will coexist nicely! It should be available on the repo in the next few days......
