### ISSUE TITLE
Author comments - Reportable and Threshold?

### ISSUE THREAD

**Issue by tommcfarlin** [postmatic/crowd#19]
Love the plugin!

Recently installed it on my own site and had one of _my own comments_ flagged and moved to moderation because the person to whom I was replying didn't like my response. It wasn't rude, inflammatory, etc., etc.

For comments left by an author, I'm not saying they shouldn't be able to be flagged (because all authors can leave bad comments, too) but perhaps increase the threshold of 'reporting' before moving it back to moderation?

**Comment by Vernal** [comment]
Not a bad idea, Tom. Maybe we can set the threshold for author-comments to
be a percentage higher than public. That might be a simple way to do so
without adding another option. What about putting it at 300% of public?

On Sat, Sep 26, 2015 at 10:01 AM, Tom McFarlin notifications@github.com
wrote:

> Love the plugin!
> 
> Recently installed it on my own site and had one of _my own comments_
> flagged and moved to moderation because the person to whom I was replying
> didn't like my response. It wasn't rude, inflammatory, etc., etc.
> 
> For comments left by an author, I'm not saying they shouldn't be able to
> be flagged (because all authors can leave bad comments, too) but perhaps
> increase the threshold of 'reporting' before moving it back to moderation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/crowd/issues/19.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by tommcfarlin** [comment]
I think that's a good place to start. It can always be tweaked in future
releases :).

Plus, it'll vary based on the level of activity on the post, I'd imagine.

-- Tom

**Comment by ronalfy** [comment]
How about this Tom since I hate options. Authors/admins/editoea cannot be reported. Filter to turn it on; threshold times 2. Filter for that too.

**Comment by ronalfy** [comment]
Tom, can you check out some changes for us? I added all in this thread to master. 

https://github.com/postmatic/crowd

**Comment by ronalfy** [comment]
Marking as closed since my changes are in branch.

**Comment by tommcfarlin** [comment]
> How about this Tom since I hate options. Authors/admins/editoea cannot be reported. Filter to turn it on; threshold times 2. Filter for that too.

I like this idea and am with you for making a decision rather than creating an option on behalf of the user. +1 for adding this :).

**Comment by Vernal** [comment]
Sweet. We'll have it out later today, Tom.

On Mon, Sep 28, 2015 at 9:06 AM, Tom McFarlin notifications@github.com
wrote:

> How about this Tom since I hate options. Authors/admins/editoea cannot be
> reported. Filter to turn it on; threshold times 2. Filter for that too.
> 
> I like this idea and am with you for making a decision rather than
> creating an option on behalf of the user. +1 for adding this :).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/crowd/issues/19#issuecomment-143738613.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
