### ISSUE TITLE
Undefined offset 242

### ISSUE THREAD

**Issue by Vernal** [postmatic/crowd#2]
Often when reporting a second comment during the same session this happens:

> Notice: Undefined offset: 242 in /home/ubuntu/workspace/wp-content/plugins/safe-report-comments/safe-report-comments.php on line 325 Call Stack: 0.0001 239120 1. {main}() /home/ubuntu/workspace/wp-admin/admin-ajax.php:0 0.2038 5112400 2. do_action() /home/ubuntu/workspace/wp-admin/admin-ajax.php:99 0.2038 5114208 3. call_user_func_array:{/home/ubuntu/workspace/wp-includes/plugin.php:503}() /home/ubuntu/workspace/wp-includes/plugin.php:503 0.2038 5114496 4. Safe_Report_Comments->flag_comment() /home/ubuntu/workspace/wp-includes/plugin.php:503 0.2053 4713632 5. Safe_Report_Comments->mark_flagged() /home/ubuntu/workspace/wp-content/plugins/safe-report-comments/safe-report-comments.php:377

**Comment by ronalfy** [comment]
Should be fixed here and I through in some necessary JS fixes as well.

https://github.com/postmatic/safe-report-comments/commit/f259fbaf190cb937e554e9f41f2be61519ee3434
