### ISSUE TITLE
Do not show Report when "Users must be registered and logged in to comment" is set unless user is logged in

### ISSUE THREAD

**Issue by phlbnks** [postmatic/crowd#21]
I had hacked "Safe Report Comments" to get it working with Epoch - then found Crowd Control. However it prints the Report button even if a user isn't logged in, and "Users must be registered and logged in to comment" is set. I consider this undesirable (to avoid comment vandalism), however I accept perhaps this could be an addition setting. 

I didn't have time to create a proper tested pull request, but knocked up a quick and ditry gist that might do the job: https://gist.github.com/emirpprime/8b4cf47f530d4119fe4f

**Comment by Vernal** [comment]
Sweet! 

I don't know how I missed this. Thanks for taking a stab at it. We'll evaluate for the upcoming release.

Jason

**Comment by ronalfy** [comment]
Fixed with: https://github.com/postmatic/crowd/commit/7c225746f9b66e48157fa9aff5b31243dd76de9b
