### ISSUE TITLE
Comments being sent to moderation

### ISSUE THREAD

**Issue by Vernal** [postmatic/crowd#22]
On certain server configurations all comments will be sent to moderation. I can't figure out why. It seems to have started on 4.4. Can reproduce on my server on site5.

Ronald, can I interest you in clocking in on this one? If not let me know.

**Comment by ronalfy** [comment]
Jason, can you please list steps to reproduce? I can't get it to work locally.

**Comment by Vernal** [comment]
Sure thing. Glad to see you! I'll have someone get you directions later today.

**Comment by erscampbell** [comment]
WordPress version: 4.4.1
Crowd Control version: 1.0.1.1

---

With the settings below, all comments for a new user are sent to moderation, even after one comment has been approved for that user:

Under Settings > Discussion:
- Before a comment appears:  
  - Comment must be manually approved: **Unchecked**
  - Comment author must have a previously approved comment: **Checked**
- Comment Moderation:
  - Hold a comment in the queue if it contains **1** or more links.
- Enable Crowd Control moderation:
  - Let site users mark comments as inappropriate: **Checked**
- Administrator notifications:
  - Send administrators an email when the crowd has sent a comment to moderation: **Checked**
- Crowd Control threshold:
  - How many reports until a comment gets sent to moderation? **3**
