### ISSUE TITLE
Wrong usage of print_flagging_link() in Epoch

### ISSUE THREAD

**Issue by Vernal** [postmatic/crowd#3]
When Epoch is activated and in the default mode (Use my typography and colors) the SRC link just reports an error of print_flagging_link(). I see nothing in the console... no idea really but my guess is it has to do with enqueuing of javascript. As I mentioned... getting into murky territory here as far as my skill set goes.

**Comment by Vernal** [comment]
The same is true of Epoch in iframe mode. Consider solving that a part of this issue as well. This may be helpful:
http://docs.gopostmatic.com/article/177-loading-third-party-scripts-in-the-epoch-iframe

**Comment by ronalfy** [comment]
https://github.com/postmatic/safe-report-comments/commit/5fd275ac69d1e7d1dbbd04671042901b897736fb

**Comment by ronalfy** [comment]
Works in iframe mode too. Forgot to mention.
